#############################################################################
# Makefile for building: qt-study.app/Contents/MacOS/qt-study
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  qt-study.pro
# Template: app
# Command: /usr/local/opt/qt5/bin/qmake -o Makefile qt-study.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.6.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.6.0/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.6.0/lib
QMAKE         = /usr/local/opt/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt-study1.0.0
DISTDIR = /Users/kenji/src/github/qt-study/.tmp/qt-study1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt5/5.6.0/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MyApp.cpp 
OBJECTS       = MyApp.o
DIST          = /usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/lex.prf \
		qt-study.pro  MyApp.cpp
QMAKE_TARGET  = qt-study
DESTDIR       = 
TARGET        = qt-study.app/Contents/MacOS/qt-study


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d qt-study.app/Contents/MacOS/ || mkdir -p qt-study.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-study.pro /usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt5/5.6.0/mkspecs/features/lex.prf \
		qt-study.pro \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt5/5.6.0/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt5/5.6.0/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile qt-study.pro
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/qdevice.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/unix.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/mac.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/macx.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/qconfig.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labscontrols_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_labstemplates_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/qt.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/resources.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/moc.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/uic.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt5/5.6.0/mkspecs/features/lex.prf:
qt-study.pro:
/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt5/5.6.0/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt5/5.6.0/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt-study.pro

qmake_all: FORCE

qt-study.app/Contents/PkgInfo: 
	@test -d qt-study.app/Contents || mkdir -p qt-study.app/Contents
	@$(DEL_FILE) qt-study.app/Contents/PkgInfo
	@echo "APPL????" > qt-study.app/Contents/PkgInfo
qt-study.app/Contents/Resources/empty.lproj: 
	@test -d qt-study.app/Contents/Resources || mkdir -p qt-study.app/Contents/Resources
	@touch qt-study.app/Contents/Resources/empty.lproj
	
qt-study.app/Contents/Info.plist: 
	@test -d qt-study.app/Contents || mkdir -p qt-study.app/Contents
	@$(DEL_FILE) qt-study.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.nextgen.qt-study,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qt-study,g" -e "s,@LIBRARY@,qt-study,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang/Info.plist.app >qt-study.app/Contents/Info.plist

all: Makefile \
		qt-study.app/Contents/PkgInfo \
		qt-study.app/Contents/Resources/empty.lproj \
		qt-study.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents MyApp.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qt-study.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all: MyApp.moc
compiler_moc_source_clean:
	-$(DEL_FILE) MyApp.moc
MyApp.moc: /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QButtonGroup \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qfiledialog.h \
		MyApp.cpp
	/usr/local/Cellar/qt5/5.6.0/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/usr/local/Cellar/qt5/5.6.0/mkspecs/macx-clang -I/Users/kenji/src/github/qt-study -I/Users/kenji/src/github/qt-study -I/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt5/5.6.0/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt5/5.6.0/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -F/usr/local/Cellar/qt5/5.6.0/lib MyApp.cpp -o MyApp.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_source_clean 

####### Compile

MyApp.o: MyApp.cpp /usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QRadioButton \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qradiobutton.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QButtonGroup \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qbuttongroup.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QSlider \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qslider.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt5/5.6.0/lib/QtWidgets.framework/Headers/qfiledialog.h \
		MyApp.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyApp.o MyApp.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

