######################################################################
# Automatically generated by qmake (3.0) ? 4? 2 17:46:21 2016
######################################################################

TEMPLATE = app
TARGET = qt-study
INCLUDEPATH += .

# Input
SOURCES += MyApp.cpp
QT += widgets
